// apps/web/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 👇 1. 引入我們的 Provider
import RailgunProvider from "@/components/providers/railgun-provider";
import WalletProvider from "@/components/providers/wallet-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Railgun Privacy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 👇 2. 用 Provider 包住 children */}
        <RailgunProvider>
          <WalletProvider> {/* 👈 加在這裡 */}
            {children}
          </WalletProvider>
        </RailgunProvider>
      </body>
    </html>
  );
}